### PR TITLE
Improvement/upstream updates

### PR DESCRIPTION
**Pull request by jsf9k**
## 🗣 Description

This pull request pulls in upstream changes from [skeleton-ansible-role](https://github.com/cisagov/skeleton-ansible-role).

## 💭 Motivation and Context

@felddy is making some changes to this Ansible role, so it makes sense to get it up to date first.

## 🧪 Testing

All pre-commit linters and molecule tests pass.

## 🚥 Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (causes existing functionality to change)

## ✅ Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by dav3r — APPROVED** [review]
Bit-rot begone!  🏓

**Review by felddy — APPROVED** [review]
AcrobaticBigEyas-small
Thank you!  A fresh start!  ✨

**Comment by felddy** [comment]
Just noticed the README still mentions the build user foo.

**Comment by jsf9k** [comment]
@felddy I will fix that.

**Comment by jsf9k** [comment]
> Just noticed the README still mentions the build user foo.

See commit 8555322.

**Comment by jsf9k** [comment]
@felddy, is the text in `README.md` about manually setting up NAT still accurate?  I haven't been doing that when I have redeployed the VPN instance.

**Comment by felddy** [comment]
> @felddy, is the text in `README.md` about manually setting up NAT still accurate? I haven't been doing that when I have redeployed the VPN instance.

It is still accurate but also handled for us in cloudinit.
See: https://github.com/cisagov/openvpn-server-tf-module/pull/21

**Pull request merged**
