### PR TITLE
Escape DN when searching LDAP with a filter

### LINKED ISSUE #6: Escape LDAP filter subjects
# 🐛 Bug Report

Users who have parenthesis (and other characters) in their PIV subjects will break the LDAP lookup in `verify-cn.py`

## To Reproduce

- Have a contractor log into the COOL

## How to fix

This is the fix:
```python
    import ldap.filter
# ...
def query_ldap(ldap_ordered_dn):
    """Query LDAP server and return True if user should be permitted."""
    con = ldap.initialize(LDAP_URI)
    con.sasl_gssapi_bind_s()
    # Convert realm into a base DN. e.g.; dc=cool,dc=cyber,dc=dhs,dc=gov
    realm_dn = ",".join([f"dc={x.lower()}" for x in REALM.split(".")])
    base_dn = f"cn=users,cn=accounts,{realm_dn}"
    vpngroup_dn = f"cn={VPN_GROUP},cn=groups,cn=accounts,{realm_dn}"
    logging.debug(f"Searching for user mapped to certificate: {ldap_ordered_dn}")
    escaped_dn = ldap.filter.escape_filter_chars(ldap_ordered_dn)
    rec = con.search_s(
        base_dn,
        ldap.SCOPE_SUBTREE,
        f"(ipaCertMapData=X509:<I>*<S>{escaped_dn})",
        attrlist=["memberOf"],
    )
    if len(rec) == 0:
        logging.warning("No matching certificate found in LDAP")
        logging.warning(f"Searched for: {ldap_ordered_dn}")
        return False

    if len(rec) > 1:
        logging.warning(f"More than 1 record found in LDAP.  Count: {len(rec)}.")
        return False

    user_dn, attribute_list = rec[0]
    logging.info(f"Found user in LDAP: {user_dn}")
    users_groups = attribute_list.get("memberOf")
    # Check to see if user is a member of the correct group
    permit_user = vpngroup_dn.encode("utf-8") in users_groups
    if permit_user:
        logging.info(f"User is member of {vpngroup_dn}")
    else:
        logging.warning(f"User IS NOT member of {vpngroup_dn}")
    return permit_user

```
This code is live on the production VPN host.  Needs to be committed to the repo.

### PR DESCRIPTION
**Pull request by felddy**
# 

## 🗣 Description
- Escape the subject before using it to search LDAP.  This broke when a contractor tried to PIV into the COOL.  The `(affiliate)` broke the search.
- Pulled in skeleton

Closes #6 

## 💭 Motivation and Context
Contractors are people too.

## 🧪 Testing

Tested in production (where it was debugged)

## 🚥 Types of Changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (causes existing functionality to change)

## ✅ Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by felddy** [comment]
Looks like `fedora31` and `fedora29` don't have `c_rehash` installed.  (Part of OpenSSL)
https://www.openssl.org/docs/man1.0.2/man1/c_rehash.html

Thoughts?

```console
    TASK [ansible-role-openvpn : Fetch DHS CA certificates using fetch_user_ca_certs.sh] ***
    fatal: [fedora31]: FAILED! => {"changed": true, "cmd": ["/etc/openvpn/server/fetch_user_ca_certs.sh"], "delta": "0:00:00.786731", "end": "2020-03-19 21:58:41.495663", "msg": "non-zero return code", "rc": 127, "start": "2020-03-19 21:58:40.708932", "stderr": "/etc/openvpn/server/fetch_user_ca_certs.sh: line 40: c_rehash: command not found", "stderr_lines": ["/etc/openvpn/server/fetch_user_ca_certs.sh: line 40: c_rehash: command not found"], "stdout": "", "stdout_lines": []}
    changed: [kali]
    changed: [debian11]
    changed: [debian10]
    fatal: [fedora29]: FAILED! => {"changed": true, "cmd": ["/etc/openvpn/server/fetch_user_ca_certs.sh"], "delta": "0:00:01.597671", "end": "2020-03-19 21:58:42.144962", "msg": "non-zero return code", "rc": 127, "start": "2020-03-19 21:58:40.547291", "stderr": "/etc/openvpn/server/fetch_user_ca_certs.sh: line 40: c_rehash: command not found", "stderr_lines": ["/etc/openvpn/server/fetch_user_ca_certs.sh: line 40: c_rehash: command not found"], "stdout": "", "stdout_lines": []}
```

**Comment by jsf9k** [comment]
@felddy, I made some changes to get rid of most of the failures.  The Debian 11 build is still failing, but that is because I don't have a systemd-enabled Debian 11 image.  I can create one tomorrow, and then everything should pass.

**Comment by felddy** [comment]
Thanks @jsf9k, no rush.

**Comment by felddy** [comment]
Just reviewed additions.  Thanks for modernizing it... This is the way™.

**Review by jsf9k — APPROVED** [review]
LGTM! :shipit:

**Review by dav3r — APPROVED** [review]
Taaaanfastic! 👍

**Pull request merged**
