### PR TITLE
Fix pip failure on Debian Bookworm

### PR DESCRIPTION
**Pull request by jsf9k**
## 🗣 Description ##

This pull request:
1. Removes a `vars` file specific to Ubuntu Xenial
2. Modifies the role to install system packages vice `pip` packages where possible
3. Adds a CLI argument to `pip` to fix [broken builds](https://github.com/cisagov/ansible-role-openvpn/actions/runs/4359384133/jobs/7634110242) on Debian Bookworm

## 💭 Motivation and context ##

1. We no longer support Ubuntu Xenial as it is EOL.
2. On Debian-based systems, newer versions of `pip` balk at installing `pip` packages under the system Python, as `pip` now (correctly) regards the system Python as "externally managed".  In general, it is better to install system packages against the system Python wherever possible.
3. This Ansible role _requires_ the installation of one `pip` package, since there is no system package available.  In order to do this on Debian Bookworm we must insist via a CLI argument that `pip` install the package against the system Python, contrary to `pip`'s better judgement.

## 🧪 Testing ##

All automated tests pass.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] *All* future TODOs are captured in issues, which are referenced in code comments.
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated to reflect the changes in this PR.
- [x] All new and existing tests pass.

### CODE REVIEW

**Comment by jsf9k** [comment]
What does @cisagov/team-ois think about creating an issue to get rid of the `srvlookup` dependency, so that we are no longer installing `pip` packages under the system python?  I think it is a good idea.

**Comment by dav3r** [comment]
> What does @cisagov/team-ois think about creating an issue to get rid of the `srvlookup` dependency, so that we are no longer installing `pip` packages under the system python? I think it is a good idea.

I'm all for it.  If we think of reasons why this is a bad idea, they can be discussed in that issue.

**Comment by jsf9k** [comment]
> > What does @cisagov/team-ois think about creating an issue to get rid of the `srvlookup` dependency, so that we are no longer installing `pip` packages under the system python? I think it is a good idea.
> 
> I'm all for it. If we think of reasons why this is a bad idea, they can be discussed in that issue.

See #71 and commit d43d19c.

**Comment by mcdonnnj** [comment]
> > > What does @cisagov/team-ois think about creating an issue to get rid of the `srvlookup` dependency, so that we are no longer installing `pip` packages under the system python? I think it is a good idea.
> > 
> > 
> > I'm all for it. If we think of reasons why this is a bad idea, they can be discussed in that issue.
> 
> See #71 and commit [d43d19c](https://github.com/cisagov/ansible-role-openvpn/commit/d43d19cddc433995c71e9d82da910b404677979b).

Commenting here to tie it together (commented on the issue already) but I think we should explore using [pipx] as this problem will be a recurrent thing when Debian Bookworm officially releases later this year (2023). Playing whack-a-mole with specific dependencies is not a long term solution in my opinion. I think using Python virtual environments directly or installing with [pipx] are better solutions to pursue.

[pipx]: https://pypa.github.io/pipx/

**Comment by jsf9k** [comment]
> > > > What does @cisagov/team-ois think about creating an issue to get rid of the `srvlookup` dependency, so that we are no longer installing `pip` packages under the system python? I think it is a good idea.
> > > 
> > > 
> > > I'm all for it. If we think of reasons why this is a bad idea, they can be discussed in that issue.
> > 
> > 
> > See #71 and commit [d43d19c](https://github.com/cisagov/ansible-role-openvpn/commit/d43d19cddc433995c71e9d82da910b404677979b).
> 
> Commenting here to tie it together (commented on the issue already) but I think we should explore using [pipx](https://pypa.github.io/pipx/) as this problem will be a recurrent thing when Debian Bookworm officially releases later this year (2023). Playing whack-a-mole with specific dependencies is not a long term solution in my opinion. I think using Python virtual environments directly or installing with [pipx](https://pypa.github.io/pipx/) are better solutions to pursue.

Noted.  At the same time, this Ansible role is broken today and this PR remedies that.  In addition, getting rid of `pip install`s on the system Python is a good thing to do even if you end up using `pipx`, [Rid-X](https://www.rid-x.com/), etc. down the line.

**Comment by mcdonnnj** [comment]
> > > > > What does @cisagov/team-ois think about creating an issue to get rid of the `srvlookup` dependency, so that we are no longer installing `pip` packages under the system python? I think it is a good idea.
> > > > 
> > > > 
> > > > I'm all for it. If we think of reasons why this is a bad idea, they can be discussed in that issue.
> > > 
> > > 
> > > See #71 and commit [d43d19c](https://github.com/cisagov/ansible-role-openvpn/commit/d43d19cddc433995c71e9d82da910b404677979b).
> > 
> > 
> > Commenting here to tie it together (commented on the issue already) but I think we should explore using [pipx](https://pypa.github.io/pipx/) as this problem will be a recurrent thing when Debian Bookworm officially releases later this year (2023). Playing whack-a-mole with specific dependencies is not a long term solution in my opinion. I think using Python virtual environments directly or installing with [pipx](https://pypa.github.io/pipx/) are better solutions to pursue.
> 
> Noted. At the same time, this Ansible role is broken today and this PR remedies that. In addition, getting rid of `pip install`s on the system Python is a good thing to do no matter what you end up doing down the line (`pipx`, [Rid-X](https://www.rid-x.com/), etc.).

Oh yeah I'm totally fine with this PR to get things going now. I'm simply talking about ways to long-term resolve this problem.

**Review by dav3r — APPROVED** [review]
🚀

**Review by mcdonnnj — APPROVED** [review]
A reasonable enough band-aid to get this working again.

**Pull request merged**
